name: LÖVE2D CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up LÖVE2D
      run: |
        sudo apt-get update
        sudo apt-get install -y love xvfb mesa-utils
    
    - name: Verify game loads
      id: verify
      run: |
        # Create a temporary .love file
    
    - name: Run tests
      run: |
        # Set up virtual framebuffer
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        
        # Run tests with headless mode
        love tests/run_tests.lua --headless