name: LÖVE2D CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up LÖVE2D
      run: |
        sudo apt-get update
        sudo apt-get install -y love xvfb mesa-utils
      
    - name: Verify game loads
      run: |
        # Roda LOVE2D com xvfb-run para ter display virtual
        xvfb-run -a love . --version
        # Try to run the game for 10 seconds to verify it opens
        timeout 10 xvfb-run -a love . || true
        echo "Jogo abriu com sucesso!"

    - name: Run tests
      run: |
        # add testes aqui
        echo "Tests completed"
