name: LÖVE2D CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up LÖVE2D
      run: |
        sudo apt-get update
        sudo apt-get install -y love xvfb mesa-utils

    - name: Run tests
      run: |
        # Set up virtual framebuffer
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        
        # Run tests with headless mode
        ALSA_CARD=none love tests/run_tests.lua --headless 2>/dev/null
    
    - name: Verify game loads
      id: verify
      run: |
        # Create a temporary directory for the game
        mkdir -p temp_game
        # Copy all files except .git, .github, and tests
        cp -r src/* temp_game/
        cp -r assets temp_game/ 2>/dev/null || true
        
        # Create a minimal test file
        echo "function love.load()
          love.event.quit()
        end" > temp_game/test_load.lua
        
        # Create the .love file from the temp directory
        cd temp_game
        zip -9 -r ../game.love .
        cd ..
        
        # Try to run the minimal test in headless mode
        if ! ALSA_CARD=none timeout 5 love game.love --headless test_load.lua 2>/dev/null; then
          echo "::error::Game failed to load properly"
          exit 1
        fi
