name: LÖVE2D CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up LÖVE2D
      run: |
        sudo apt-get update
        sudo apt-get install -y love xvfb mesa-utils libasound2-plugins
        # Configura o ALSA para usar um dispositivo de áudio nulo
        echo "pcm.!default { type null }" | sudo tee /etc/asound.conf
        echo "ctl.!default { type null }" | sudo tee -a /etc/asound.conf
        # Mostra onde o LÖVE está instalado
        which love
        ls -l $(which love)
      
    - name: Verify game loads
      run: |
        # Roda LOVE2D com xvfb-run para ter display virtual
        xvfb-run -a /usr/bin/love "$(pwd)" --version
        # Try to run the game for 5 seconds to verify it opens
        timeout 5 xvfb-run -a /usr/bin/love "$(pwd)" || true
        echo "Jogo abriu com sucesso!"

    - name: Run tests
      run: |
        # add testes aqui
        echo "Tests completed"
